source 'https://github.com/Artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
platform :osx, '13.0'
use_frameworks! :linkage => :static

target 'Swiftline-Example' do
    pod 'Swiftline', :path => '../Swiftline.podspec'
end



post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["MACOSX_DEPLOYMENT_TARGET"] = "13.0"
    end
  end
end


